"""
Generation metadata for nf-docs output.

Provides version, timestamp, and attribution information for generated documentation.
"""

from datetime import datetime, timezone

from nf_docs import __version__

# URLs for attribution
NEXTFLOW_URL = "https://nextflow.io"
NFDOCS_REPO_URL = "https://github.com/ewels/nf-docs"


def get_generation_info() -> dict[str, str]:
    """
    Get metadata about the documentation generation.

    Returns:
        Dictionary containing:
        - nf_docs_version: Version of nf-docs used
        - generated_at: ISO 8601 timestamp of generation
        - nextflow_url: URL to Nextflow website
        - nf_docs_url: URL to nf-docs repository
    """
    return {
        "nf_docs_version": __version__,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "nextflow_url": NEXTFLOW_URL,
        "nf_docs_url": NFDOCS_REPO_URL,
    }


def get_generation_timestamp() -> str:
    """Get a human-readable timestamp for the generation time."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def get_markdown_footer() -> str:
    """
    Get a footer for Markdown files.

    Returns:
        Markdown-formatted footer string
    """
    info = get_generation_info()
    timestamp = get_generation_timestamp()

    return f"""---

*This pipeline was built with [Nextflow]({NEXTFLOW_URL}).
Documentation generated by [nf-docs]({NFDOCS_REPO_URL}) v{info["nf_docs_version"]} on {timestamp}.*
"""
